<?php namespace EvolutionCMS\Console\Packages;

use Illuminate\Console\Command;
use \EvolutionCMS;
use Illuminate\Support\Facades\File;

/**
 * PackageCommand - Discover and register ServiceProviders from custom packages
 *
 * This command scans composer.json files and generates provider config files
 * in core/custom/config/app/providers/ directory.
 *
 * Provider Priority System:
 * -------------------------
 * Providers can specify load priority in their composer.json:
 *
 * "extra": {
 *     "laravel": {
 *         "providers": ["Vendor\\Package\\SomeServiceProvider"],
 *         "priority": {
 *             "Vendor\\Package\\SomeServiceProvider": 1
 *         }
 *     }
 * }
 *
 * Priority 1-999: Creates file with prefix (e.g., 001_SomeServiceProvider.php)
 * Priority 0 (or not specified): Creates file without prefix
 *
 * Files are loaded in alphabetical order, so:
 * - 001_sLangServiceProvider.php loads first (priority: 1)
 * - 050_SomeOtherProvider.php loads second (priority: 50)
 * - sCommerceServiceProvider.php loads third (priority: 0 or not specified)
 * - etc.
 *
 * @package EvolutionCMS\Console\Packages
 */
class PackageCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'package:discover';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate ServiceProviders for custom packages';
    /**
     * Path for custom providers
     * @var string
     */
    protected $configDir = EVO_CORE_PATH . 'custom/config/app/providers/';
    /**
     * Path for custom aliases
     * @var string
     */
    protected $aliasesDir = EVO_CORE_PATH . 'custom/config/app/aliases/';
    /**
     * Track aliases generated during current discovery run.
     * @var array<string,bool>
     */
    protected $discoveredAliasFiles = [];

    /**
     * Marker used to identify auto-generated alias files.
     * @var string
     */
    protected $aliasMarker = 'Generated by package:discover';
    /**
     * Custom composer.json
     * @var string
     */
    protected $composer = EVO_CORE_PATH . 'custom/composer.json';
    /**
     * @var string
     */
    public $packagePath = '';

    /**
     * @var mixed|string
     */
    public $load_dir = '';

    /**
     * @var \DocumentParser|string
     */
    public $evo = '';

    /**
     * Packages currently being traversed during recursive provider discovery.
     *
     * @var array<string,bool>
     */
    protected $visitingPackages = [];

    /**
     * Packages whose dependencies and provider metadata were already processed.
     *
     * @var array<string,bool>
     */
    protected $discoveredPackages = [];

    /**
     * Packages listed directly in core/custom/composer.json.
     *
     * @var array<string,bool>
     */
    protected $rootRequiredPackages = [];

    /**
     * Parent packages that required a package during recursive discovery.
     *
     * @var array<string,array<string,bool>>
     */
    protected $packageDependents = [];

    /**
     * PackageCommand constructor.
     */
    public function __construct()
    {
        parent::__construct();
        $this->evo = evo();
        $this->load_dir = $this->evo->getConfig('rb_base_dir');
    }

    /**
     * Execute the console command.
     *
     * @return void
     */
    public function handle()
    {
        if (!is_dir($this->configDir)) {
            mkdir($this->configDir, 0775, true);
        }
        if (!is_dir($this->configDir)) {
            $this->getOutput()->write('<error>ERROR CREATE CONFIG DIR</error>');
            exit();
        }

        if (!is_dir($this->aliasesDir)) {
            mkdir($this->aliasesDir, 0775, true);
        }
        if (!is_dir($this->aliasesDir)) {
            $this->getOutput()->write('<error>ERROR CREATE ALIASES DIR</error>');
            exit();
        }

        if (file_exists($this->composer)) {
            $this->parseComposer($this->composer);
        }
        $this->cleanupAliases();

        unlink(EVO_CORE_PATH . 'storage/bootstrap/services.php');
    }

    /**
     * Discover providers declared by the custom Composer root and its packages.
     *
     * Installed package requirements are traversed recursively so dependencies
     * register their providers before the packages that depend on them.
     *
     * @param string $composer Absolute path to the custom composer.json file.
     */
    public function parseComposer(string $composer)
    {
        $data = json_decode(file_get_contents($composer), true);
        $this->rootRequiredPackages = [];
        $this->packageDependents = [];
        $this->visitingPackages = [];
        $this->discoveredPackages = [];

        if (isset($data['extra']['laravel']['providers'])) {
            // Get priorities if defined (default to empty array if not present)
            $priorities = $data['extra']['laravel']['priority'] ?? [];

            foreach ($data['extra']['laravel']['providers'] as $value) {
                // Get priority for this provider (default 0 if not specified)
                $priority = $priorities[$value] ?? 0;
                $this->process($value, $priority);
            }
        }

        if (isset($data['extra']['laravel']['aliases']) && is_array($data['extra']['laravel']['aliases'])) {
            foreach ($data['extra']['laravel']['aliases'] as $alias => $class) {
                $this->processAlias((string) $alias, (string) $class);
            }
        }

        if (isset($data['require']) && is_array($data['require'])) {
            $this->rootRequiredPackages = array_fill_keys(
                array_map(fn ($package) => strtolower(trim((string) $package)), array_keys($data['require'])),
                true
            );

            foreach ($data['require'] as $key => $value) {
                $this->discoverPackage((string) $key);
            }
        }
        if (isset($data['autoload']['psr-4'])) {
            foreach ($data['autoload']['psr-4'] as $key => $value) {
                $composer = EVO_CORE_PATH . 'custom/' . $value . '/composer.json';
                $this->packagePath = EVO_CORE_PATH . 'custom/' . $value . '/';
                if (file_exists($composer)) {
                    $this->parseComposerServiceProvider($composer);
                }

            }
        }
    }

    /**
     * @param string $composer
     */
    public function parseComposerServiceProvider(string $composer)
    {
        $data = json_decode(file_get_contents($composer), true);
        if (isset($data['extra']['laravel']['providers']) && is_array($data['extra']['laravel']['providers'])) {
            // Get priorities if defined (default to empty array if not present)
            $priorities = $data['extra']['laravel']['priority'] ?? [];

            foreach ($data['extra']['laravel']['providers'] as $value) {
                // Get priority for this provider (default 0 if not specified)
                $priority = $priorities[$value] ?? 0;
                $this->process($value, $priority);
            }
        }

        if (isset($data['extra']['laravel']['aliases']) && is_array($data['extra']['laravel']['aliases'])) {
            foreach ($data['extra']['laravel']['aliases'] as $alias => $class) {
                $this->processAlias((string) $alias, (string) $class);
            }
        }

        if (isset($data['extra']['laravel']['files'])) {
            foreach ($data['extra']['laravel']['files'] as $copyArray) {
                $this->copyFiles($copyArray);
            }
        }
    }

    /**
     * Generate provider config file with optional priority prefix
     *
     * @param string $value Provider class name
     * @param int $priority Priority (1-999), used for load order. Lower numbers load first.
     */
    protected function process(string $value, int $priority = 0)
    {
        $arrNamespace = explode('\\', $value);
        $className = end($arrNamespace);

        // Add priority prefix if specified (001_, 002_, ..., 999_)
        if ($priority > 0 && $priority < 1000) {
            $prefix = str_pad($priority, 3, '0', STR_PAD_LEFT) . '_';
            $fileName = $prefix . $className . '.php';
            $fileContent = "<?php\n// Priority {$priority} - loads before other providers\nreturn " . $value . "::class;";

            // Remove old files with different prefixes for the same provider
            $patterns = [
                $this->configDir . $className . '.php',                    // without prefix
                $this->configDir . '*_' . $className . '.php',             // with any prefix
            ];

            foreach ($patterns as $pattern) {
                foreach (glob($pattern) as $oldFile) {
                    if ($oldFile !== $this->configDir . $fileName) {
                        @unlink($oldFile);
                        $this->getOutput()->write('<comment>Removed old ' . basename($oldFile) . ' (using priority prefix)</comment>');
                    }
                }
            }
        } else {
            $fileName = $className . '.php';
            $fileContent = "<?php \nreturn " . $value . "::class;";
        }

        if (file_put_contents($this->configDir . $fileName, $fileContent)) {
            $this->getOutput()->write('<info>' . $value . ($priority > 0 ? " (priority: {$priority})" : '') . '</info>');
        } else {
            $this->getOutput()->write('<error>Error create config for: ' . $value . '</error>');
        }
        $this->line('');
    }

    /**
     * Generate alias config file for custom packages.
     *
     * Creates core/custom/config/app/aliases/<Alias>.php which returns FQCN::class.
     */
    protected function processAlias(string $alias, string $class): void
    {
        $alias = trim($alias);
        $class = trim($class);

        if ($alias === '' || $class === '') {
            return;
        }

        // Keep it safe for filesystem (e.g. "sApi" -> "sApi.php")
        $fileName = preg_replace('~[^A-Za-z0-9_]+~', '', $alias) . '.php';
        if ($fileName === '.php') {
            return;
        }

        $this->discoveredAliasFiles[$fileName] = true;

        $content = "<?php\n// {$this->aliasMarker}\nreturn {$class}::class;\n";
        @file_put_contents($this->aliasesDir . $fileName, $content);
    }

    /**
     * Remove auto-generated alias files that are no longer discovered.
     *
     * This makes aliases self-healing when packages are removed.
     */
    protected function cleanupAliases(): void
    {
        foreach (glob($this->aliasesDir . '*.php') as $file) {
            $baseName = basename($file);
            if (isset($this->discoveredAliasFiles[$baseName])) {
                continue;
            }

            $contents = @file_get_contents($file);
            if (!is_string($contents) || $contents === '') {
                continue;
            }

            if (strpos($contents, $this->aliasMarker) === false) {
                continue;
            }

            @unlink($file);
        }
    }

    /**
     * @param array $copyArray
     */
    protected function copyFiles(array $copyArray)
    {
        File::copyDirectory($this->packagePath . $copyArray['source'], $this->load_dir . $copyArray['destination']);
    }

    /**
     * Recursively discover one installed package in dependency-first order.
     *
     * Visiting and discovered sets make shared dependencies idempotent and stop
     * circular Composer requirements without package-specific exceptions.
     *
     * @since 3.5.8
     * @param string $package Composer package name.
     * @return void
     */
    protected function discoverPackage(string $package, string $requiredBy = ''): void
    {
        $package = strtolower(trim($package));
        $requiredBy = strtolower(trim($requiredBy));
        if ($package !== '' && $requiredBy !== '') {
            $this->packageDependents[$package][$requiredBy] = true;
        }

        if ($package === '' || isset($this->discoveredPackages[$package]) || isset($this->visitingPackages[$package])) {
            return;
        }

        $this->visitingPackages[$package] = true;
        $composer = $this->packageComposerPath($package);

        if (is_file($composer)) {
            $composerArray = json_decode((string) file_get_contents($composer), true);

            if (isset($composerArray['require']) && is_array($composerArray['require'])) {
                foreach (array_keys($composerArray['require']) as $dependency) {
                    $this->discoverPackage((string) $dependency, $package);
                }
            }

            $this->packagePath = dirname($composer) . '/';
            $this->warnAboutTransitivePackage($package, $composerArray);
            $this->parseComposerServiceProvider($composer);
        }

        unset($this->visitingPackages[$package]);
        $this->discoveredPackages[$package] = true;
    }

    /**
     * Resolve the installed composer.json path for a package.
     *
     * Kept separate from traversal so package graph fixtures can exercise the
     * resolver without writing into the real vendor directory.
     *
     * @since 3.5.8
     * @param string $package Normalized Composer package name.
     * @return string Absolute path to the installed package metadata.
     */
    protected function packageComposerPath(string $package): string
    {
        return EVO_CORE_PATH . 'vendor/' . $package . '/composer.json';
    }

    /**
     * Warn when a provider-bearing package remains discovered as a transitive dependency.
     *
     * @since 3.5.8
     * @param string $package Composer package name.
     * @param array|null $composer Package composer metadata.
     * @return void
     */
    protected function warnAboutTransitivePackage(string $package, ?array $composer): void
    {
        if (isset($this->rootRequiredPackages[$package]) || empty($this->packageDependents[$package])) {
            return;
        }

        if (!$this->hasLaravelDiscoveryMetadata($composer)) {
            return;
        }

        $dependents = implode(', ', array_keys($this->packageDependents[$package]));
        $this->warn('Package ' . $package . ' is still discovered because it is required by ' . $dependents . '.');
    }

    /**
     * Determine whether a package contributes discovery output.
     *
     * @since 3.5.8
     * @param array|null $composer Package composer metadata.
     * @return bool
     */
    protected function hasLaravelDiscoveryMetadata(?array $composer): bool
    {
        $laravel = $composer['extra']['laravel'] ?? null;
        if (!is_array($laravel)) {
            return false;
        }

        foreach (['providers', 'aliases', 'files'] as $key) {
            if (!empty($laravel[$key]) && is_array($laravel[$key])) {
                return true;
            }
        }

        return false;
    }
}
